-- Etapa 1: enlaces cortos (ver docs/arquitectura.md, sección 4, y ADR-0021).
-- Un único registro por alias: un alias vencido se reasigna actualizando su fila.
-- Las fechas se guardan en UTC (Hibernate mapea java.time.Instant a TIMESTAMP normalizado a UTC).
CREATE TABLE link (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias        VARCHAR(16)   NOT NULL,
    original_url VARCHAR(2048) NOT NULL,
    created_at   TIMESTAMP(6)  NOT NULL,
    expires_at   TIMESTAMP(6)  NOT NULL,
    CONSTRAINT uk_link_alias UNIQUE (alias)
);
